Added pypi plugin which is used for uploading own python packages in pypi
ohmyzsh/ohmyzsh pull request #10007
Opened 2021-06-26 11:31 UTC by ToastCoder

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:

The plugin is used especially for python developers who work on uploading or testing their own python packages. This plugin is used to simplifying the commands which have to be executed every time.

2021-06-26 14:42 UTC, TheTechRobo requested changes
just have some thoughts

2021-06-26 14:42 UTC, TheTechRobo commented on plugins/pypi/pypi.plugin.zsh
> +alias pypi-check='pip3 install twine setuptools'
maybe use `python3 -m pip`?

2021-06-26 15:40 UTC, ToastCoder commented on plugins/pypi/pypi.plugin.zsh
> +alias pypi-check='pip3 install twine setuptools'
I have updated, sir.

2021-06-27 18:42 UTC, hjpotter92 commented
perhaps a few more aliases for build/test/install [from setuptools](https://pythonhosted.org/an_example_pypi_project/setuptools.html#using-setup-py).

the `pypi-ltest` is confusing, as my initial thought seeing it was this subcommand:

>   `test`              run unit tests after in-place build

2021-06-28 13:07 UTC, ToastCoder commented
`pypi-ltest` is the alias used for testing the python package in the local machine, so that you don't have to upload it to pypi if you haven't tested it yet.

2021-11-13 14:22 UTC, ToastCoder commented
Could someone at least have a look at the PR? In case if there's anything which I could improve, mentioning them would be great.

2021-11-13 14:28 UTC, TheTechRobo commented
as you can see at the top, there are a LOT of pending pull requests. this one will be reviewed eventually by the maintainers.

if you want to expedite it, you might want to ask on the discord server.

2022-07-04 04:39 UTC, NeilGirdhar commented
Should this be called twine or pypi?

2026-09-09 00:10 UTC, robbyrussell commented
Thanks for putting this together, and sorry for the very long delay in replying.

A plugin that's four aliases around twine is more of a personal setup than something we'd want every user to enable, and the `setup.py sdist` calls it wraps have since been deprecated by the Python packaging folks. Two people also raised naming questions here in 2021 that never got resolved.

This works well as a custom plugin in `$ZSH_CUSTOM`. That's a supported setup and it'll survive updates.

Closing for that reason. Thanks again for contributing.

2026-09-09 00:10 UTC, closed without merging