feat(multipass): add plugin for multipass
ohmyzsh/ohmyzsh pull request #10140
Opened 2021-08-25 22:02 UTC by xlith

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- This new plugin provides completion for [multipass](https://multipass.run), as well as aliases for multipass commands

Fixes #9124

2022-01-27 12:51 UTC, h4ux reviewed
It's a great first version for multipass completion

2022-01-28 18:25 UTC, mcornella commented
Can you rename the plugin to `multipass`?

2022-01-28 22:01 UTC, mcornella requested changes
Some changes needed, as well as changing the name of the plugin to `multipass`.

2022-01-28 22:01 UTC, mcornella commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> +    $_comp_command1 | sed "1,/Available commands/d" | awk '/^[ \t]*[a-z]+/ { print $1 }'
Use 2-space indentation.

2022-01-28 22:01 UTC, mcornella commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> +_multipass () {
nitpick: missing a space.

2022-01-28 22:01 UTC, mcornella commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> +alias mpln="multipass launch --network en0 --network name=bridge0,mode=manual"
These should be alphabetically sorted.

2022-02-01 21:23 UTC, xlith commented on plugins/zsh-multipass/README.md
> +
Done!

2022-02-01 21:23 UTC, xlith commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> +compdef _multipass multipass
Done!

2022-02-01 21:23 UTC, xlith commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> +alias mpln="multipass launch --network en0 --network name=bridge0,mode=manual"
Done!

2022-02-01 21:23 UTC, xlith commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> +_multipass () {
Done!

2022-02-01 21:24 UTC, xlith commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> +    $_comp_command1 | sed "1,/Available commands/d" | awk '/^[ \t]*[a-z]+/ { print $1 }'
Done!

2022-02-01 21:24 UTC, xlith commented on plugins/zsh-multipass/zsh-multipass.plugin.zsh
> + # $_comp_command1 list | tail -1 | awk '/^[ \t]*[a-z]+/ { print $1 }'
Done!

2022-02-01 21:25 UTC, xlith commented
Thanks for the review. All of them should be fixed now. Please let me know if I need to do anything else.

2022-02-01 22:47 UTC, mcornella approved these changes

2022-02-01 22:48 UTC, merged

2022-02-01 22:48 UTC, mcornella commented
Thanks Civan! And apologies for the delay!