Fixes #10365. Add bloop plugin
ohmyzsh/ohmyzsh pull request #10366
Opened 2021-10-30 21:17 UTC by ankusharya

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Other comments:
This pull request adds plugin `bloop` which is a list of frequent [bloop](https://scalacenter.github.io/bloop/) commands.

2021-10-31 01:51 UTC, bradchristensen requested changes
I don't know what bloop is, but I happened to be browsing through PRs and noticed these minor things could be fixed 😄

2021-10-31 01:51 UTC, bradchristensen commented on plugins/bloop/README.md
> +The plugin adds several aliases for common [bloop](https://https://scalacenter.github.io/bloop/) commands.
Typo on the URL here:

```suggestion
The plugin adds several aliases for common [bloop](https://scalacenter.github.io/bloop/) commands.
```

2021-10-31 01:51 UTC, bradchristensen commented on plugins/bloop/README.md
> +| `br`     | `brew run `                           | Run the project                                                     |
I assume you mean `bloop` in each of these cases:

```suggestion
| `bp`     | `bloop projects`                      | List the projects in current repository                             |
| `bc`     | `bloop compile `                      | Compile the project                                                 |
| `bcl`    | `bloop clean `                        | Clean the project                                                   |
| `br`     | `bloop run `                          | Run the project                                                     |
```

2021-10-31 09:18 UTC, ankusharya commented
@bradchristensen I have corrected my mistakes based on your suggestion. Please review once again.

2021-10-31 19:48 UTC, bradchristensen approved these changes

2021-12-02 15:50 UTC, jsoref commented
Hi, you're going to need to rebase this PR onto master in order to pass the spell checker which is going to ask you to add lines to `.github/actions/spelling/expect.txt`:

```
bcl
scalacenter
```

(You can insert them alphabetically, or just place them somewhere.)

2026-09-09 00:41 UTC, robbyrussell commented
Thanks for this, and sorry for the long delay.

Bloop already ships its own zsh completions, so most of what a plugin here would add is available without us carrying it. The four aliases also collide with ones we already have: `bp` from bundler, `bcl` and `br` from brew.

Closing for that reason. `$ZSH_CUSTOM` is a good home for the aliases you like, and it survives updates.

2026-09-09 00:41 UTC, closed without merging