Adding charm plugin
ohmyzsh/ohmyzsh pull request #10803
Opened 2022-03-28 00:46 UTC by mamercad

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add completions from `charm completion zsh`

## Other comments:

N/A

2022-03-28 06:26 UTC, carlosala requested changes

2022-03-28 06:26 UTC, carlosala commented on plugins/charm/charm.plugin.zsh
> +# TODO: 2021-12-28: remove this block
You can remove from here to line 18 :)

2022-03-29 06:31 UTC, carlosala approved these changes

2022-03-29 09:45 UTC, mcornella approved these changes

2022-03-29 09:45 UTC, merged

2022-03-29 09:45 UTC, mcornella commented
Thanks!