feat(tmux): change prefix on ssh
ohmyzsh/ohmyzsh pull request #10848
Opened 2022-04-12 19:29 UTC by njfamirm

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- change prefix on ssh

## Other comment

fix #10847

2022-04-13 12:25 UTC, mcornella commented
This should be documented somewhere and made configurable.

2022-04-14 02:53 UTC, njfamirm commented
OK @mcornella ?

2022-04-14 20:27 UTC, njfamirm commented
> This should be documented somewhere and made configurable.

completed! @mcornella

2022-04-20 05:49 UTC, njfamirm commented
Ok?

2022-04-28 18:14 UTC, njfamirm commented
```bash
echo '@njfamirm' >> .userignore 
```

2022-04-28 18:16 UTC, njfamirm commented
If there is a problem, please let me know!

@mcornella @carlosala

2022-05-17 08:24 UTC, njfamirm commented
Please review @mcornella

2022-06-13 19:40 UTC, njfamirm commented
Unfortunately, after re-examining, I realized that two tmux have problems with each other!

2022-06-17 09:01 UTC, njfamirm commented
I made a mistake
It works perfectly!

2022-06-23 20:41 UTC, bhushan requested changes

2022-06-23 20:41 UTC, bhushan commented on plugins/tmux/README.md
> +| `ZSH_TMUX_UNICODE`                  | Set `tmux -u` option to support unicode                                                            |
unrelated changes

2022-06-24 00:19 UTC, njfamirm commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
What is your suggestion?
There is no insistence on this shortcut
Anything can be

2022-06-24 00:22 UTC, njfamirm commented on plugins/tmux/README.md
> +| `ZSH_TMUX_UNICODE`                  | Set `tmux -u` option to support unicode                                                            |
for formating

2022-06-24 00:22 UTC, njfamirm commented
Thanks for the review!

2022-06-26 16:39 UTC, bhushan commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
Is there a way we can temporarily u bind local prefix.. And use only server tmux.. And once we are back to local tmux set back whatever it was before?

2022-06-26 19:17 UTC, njfamirm commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
It's wrong, We may need to use tmux locally as well!

2022-06-26 19:20 UTC, njfamirm commented
V near the B [default prefix key]

2022-06-26 20:10 UTC, bhushan commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
It might be wrong. But what if the user has ‘C-v’ already set as a prefix locally.    Then we’ll have same problem. I am concerned about this.

2022-06-26 20:12 UTC, bhushan commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
Or is it possible to check if ‘C-v’ is a prefix locally and then set ‘C-b’ on the server and vice versa? Will it be possible to make it work?

2022-06-26 20:21 UTC, njfamirm commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
yes, I fix it

2022-06-26 20:22 UTC, njfamirm commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
set ZSH_TMUX_PREFIX_ON_SSH2 and check if prefix key or prefix2 key equal to ZSH_TMUX_PREFIX_ON_SSH then use ZSH_TMUX_PREFIX_ON_SSH2

2022-07-04 19:41 UTC, njfamirm commented on plugins/tmux/tmux.plugin.zsh
> +: ${ZSH_TMUX_PREFIX_ON_SSH:="C-w"}
I made a mistake!
It's not possible to access the local prefix from the server
So, users can fix by change ZSH_TMUX_PREFIX_ON_SSH in zshconf manually

2022-07-04 19:44 UTC, njfamirm commented
@mcornella @bhushan

2022-08-17 17:54 UTC, njfamirm commented
why comment removed?!

2022-08-28 05:43 UTC, closed without merging