feat(tmux): add `$ZSH_TMUX_SKIP_CONFIG`
ohmyzsh/ohmyzsh pull request #10986
Opened 2022-06-11 05:18 UTC by thanhnguyen2187

Resolve #10367

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Add `$ZSH_TMUX_SKIP_CONFIG` to skip `$ZSH_TMUX_CONFIG` usage

## Other comments:

...

2022-06-26 20:20 UTC, bhushan requested changes

2022-06-26 20:20 UTC, bhushan commented on plugins/tmux/tmux.plugin.zsh
> +    if [[ "$ZSH_TMUX_FIXTERM" == "true" "$ZSH_TMUX_SKIP_CONFIG" == "false" ]]; then
```suggestion
    if [[ "$ZSH_TMUX_FIXTERM" == "true" && "$ZSH_TMUX_SKIP_CONFIG" == "false" ]]; then
```

2022-07-17 19:31 UTC, njfamirm approved these changes

2026-09-10 17:36 UTC, robbyrussell commented
Thanks for this, and sorry it sat unanswered for so long. The config lookup was rewritten in #11103, so the plugin now finds `$XDG_CONFIG_HOME/tmux/tmux.conf` on its own, and #10367 was closed last week as not achievable.

Closing for that reason rather than because the idea was wrong.

2026-09-10 17:36 UTC, closed without merging