Update README.md
ohmyzsh/ohmyzsh pull request #11204
Opened 2022-10-01 06:48 UTC by siddhant2202

Updated README Document with correcting all grammatical error using Grammarly

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- [...]

## Other comments:

...

2022-10-01 13:23 UTC, LunarWatcher requested changes

2022-10-01 13:23 UTC, LunarWatcher commented on README.md
> -  macos
No. `plugins` is case-sensitive

2022-10-01 13:23 UTC, LunarWatcher commented on README.md
> -Once installed, your terminal shell will become the talk of the town _or your money back!_ With each keystroke in your command prompt, you'll take advantage of the hundreds of powerful plugins and be
Spaces at the start of a quote isn't good grammar, nor an improvement

2022-10-02 14:01 UTC, mcornella commented
Can you apply the changes suggested?

2022-10-04 01:33 UTC, Clash-ion commented
Can i take this issue?

2022-10-04 08:50 UTC, LunarWatcher commented
This is a pull request, not an issue

2022-11-07 18:32 UTC, closed without merging