Add doas support in sudo plugin.
ohmyzsh/ohmyzsh pull request #11395
Opened 2022-12-16 21:01 UTC by 154pinkchairs

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add non-interactive  (dependent on whether sudo is present in the system) support for doas in sudo plugin, as suggested in PR#8669

## Other comments:

Tested under Alpine Linux 3.17
@mcornella 

...

2022-12-17 11:12 UTC, carlosala requested changes

2022-12-17 11:12 UTC, carlosala commented on plugins/sudo/sudo.plugin.zsh
> +        $ROOT_COMMAND\ -e\ *) __sudo-replace-buffer "sudo -e" "" ;;
`doas -e` does not exist.

2022-12-17 11:12 UTC, carlosala commented on plugins/sudo/sudo.plugin.zsh
> +      $ROOT_COMMAND\ -e\ *) __sudo-replace-buffer "sudo -e" "$EDITOR" ;;
same happens here

2022-12-17 11:12 UTC, carlosala commented on plugins/sudo/sudo.plugin.zsh
> +  ROOT_COMMAND=sudo
It's better to use `zstyle` options for configurability. You can check, for example, `nvm` plugin to see how are we doing this lately 👌🏻

2022-12-17 11:17 UTC, carlosala requested changes
We'd also need an explanation about this in README

2024-02-29 21:24 UTC, closed without merging

2024-02-29 21:24 UTC, carlosala commented
Hi! This PR doesn't seem to get a lot of traction, and it seems stale. Closing, thanks for the contribution!

2024-02-29 23:10 UTC, mjholub commented
yeah I switched to Fish long time ago anyway, sorry, forgot about that one

2024-02-29 23:13 UTC, carlosala commented
Np! Thanks for your contribution!