add support for macOS
ohmyzsh/ohmyzsh pull request #11391
Opened 2022-12-15 02:03 UTC by rwmitchell

This can probably be improved with better lsof and zsh zen, but it works reasonably well on my system.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- [x] use lsof, grep, and awk to generate list of CWDs of zsh sessions to support macOS that lacks /proc 

## Other comments:

...

2023-01-05 22:48 UTC, grimm26 requested changes
Please follow the commit guidelines https://github.com/ohmyzsh/ohmyzsh/blob/master/CONTRIBUTING.md#commit-guidelines especially in making your commit message and PR title.  Thanks.

2023-01-06 12:59 UTC, mcornella commented
Using the man page for lsof I found the following command that will automatically select only zsh processes and print the directories on each line, which works for directories with spaces:
```
lsof -d cwd -c zsh -a -w -Fn | sed -n 's/^n//p'
```

Pending to check if it works for macOS lsof.

2023-01-06 13:20 UTC, rwmitchell commented
Your change works on my system:

darwin*)  dirs=( $( lsof -d cwd -c zsh -a -w -Fn | sed -n 's/^n//p' ) ) ;;

2023-04-04 21:52 UTC, merged

2023-04-04 21:52 UTC, mcornella commented
Sorry for forgetting about this, thanks for applying my suggestion!