feat(iterm2): Add iTerm2 shell integration script
ohmyzsh/ohmyzsh pull request #11509
Opened 2023-02-21 13:00 UTC by reegnz

Mirror the official script and source it with the iterm2 plugin.

The integration script brings features like automatic marks on each prompt, drag and drop scp support, or automatic profile switching.

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- [...]

## Other comments:

...

2023-02-21 13:02 UTC, reegnz commented
@avivrosenberg

2023-02-22 09:28 UTC, carlosala commented
in terms of license, it is ok. Even though, I'd make it opt-in, using `zstyle`. You can see how to do this in `nvm` plugin, for example.

2023-02-22 12:58 UTC, reegnz commented
I'm not sure about the opt-in, I think the shell-integration is quite essential when using iterm2. If the concern is that existing users that use iterm2 plugin don't want to be surprised by having it enabled, that's fair. I don't think it's backward-incompatible change though, so it won't break anything IMHO.

So sure, I can add a zstyle if it makes it easier to get merged.

2023-02-22 14:18 UTC, carlosala requested changes

2023-02-22 14:18 UTC, carlosala commented on plugins/iterm2/README.md
> +zstyle :omz:plugins:iterm2 shell-integration true
Please change `true` with `yes`.

2023-02-24 16:02 UTC, reegnz commented on plugins/iterm2/README.md
> +zstyle :omz:plugins:iterm2 shell-integration true
Fixed

2023-02-24 16:27 UTC, merged

2023-02-24 16:27 UTC, carlosala commented
Thanks for your contribution!