fix(macos): update shpotify script
ohmyzsh/ohmyzsh pull request #11534
Opened 2023-03-02 02:33 UTC by sobeckley

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

This script is a copy/paste from https://github.com/hnarayanan/shpotify (the plugin's acknowledgements list it as such). The upstream script has been updated since this plugin was created, this PR pulls in those changes to this plugin.

## Other comments:

I noticed the version bundled in this plugin does not work with the latest version of Spotify, however the upstream does. Hopefully this will resolve that discrepancy.

2023-03-03 14:05 UTC, carlosala requested changes

2023-03-03 14:05 UTC, carlosala commented on plugins/macos/spotify
> -function spotify() {
This should not be removed, we are sourcing that on main plugin file.

2023-03-03 14:05 UTC, carlosala commented on plugins/macos/spotify
> +		exit 1
We changed on purpose all exits to return, could you revert that?

2023-03-03 14:05 UTC, carlosala commented on plugins/macos/spotify
> -            break ;;
Same here, it should be break.

2023-03-03 14:05 UTC, carlosala commented on plugins/macos/spotify
> -}
This should not be removed.

2023-09-10 22:43 UTC, sobeckley commented
@carlosala Apologies for the extended delay. This should be ready for another look whenever you have a moment.

2023-09-11 07:35 UTC, merged

2023-09-11 07:35 UTC, carlosala commented
Thanks!