Added verbose flag to update.sh (issue #11574)
ohmyzsh/ohmyzsh pull request #11579
Opened 2023-03-24 11:48 UTC by haabe

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Sources settings from $HOME/.zshrc to read :omz:update verbose
- Sets verbose_mode to default if not set
- Dependant text rendering based on verbose_mode

## Other comments:
- .zshrc probably should have a mention of :omz:update verbose if implemented
- docs probably should have a mention of :omz:update verbose if implemented
...

2023-03-24 13:22 UTC, carlosala commented on tools/upgrade.sh
> +if [[ "$verbose_mode" != silent ]]
missing `; then`

2023-03-24 13:22 UTC, carlosala commented on tools/upgrade.sh
> +    if [[ "$verbose_mode" != silent ]]
missing `; then`

2023-03-24 13:22 UTC, carlosala commented on tools/upgrade.sh
> +  if [[ "$verbose_mode" = default]]
let's go for `==` and a space after default, and `; then`

2023-03-25 08:08 UTC, carlosala requested changes
I'll test a bit more and get back. In the meantime, could you also document this feature in main README?

2023-03-25 08:08 UTC, carlosala commented on tools/upgrade.sh
> +  if [[ "$verbose_mode" == default]]; then
A space missing after `default`

2023-03-26 21:57 UTC, haabe commented
So I rewrote it to pass an argument together with --interactive in the cli - and fixed my impressively embarrassing `; then` bugs. I also added a few lines about the config in README.md.

2023-03-28 10:58 UTC, closed without merging

2023-03-28 10:59 UTC, carlosala commented
Thanks for your contribution! I changed a few things that made sense for me, but the functionality is there! Thanks for your contribution!