Feat(agnoster) Add terraform workspace name prompt support. Plugins terraform-workspace-prompt)
ohmyzsh/ohmyzsh pull request #11610
Opened 2023-04-11 02:46 UTC by ocontant

## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.
- [X] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add support to display terraform workspace name in Agnoster theme prompt.
- The change is designed to support the plugin terraform-workspace-prompt

## Other comments:
There is currently no plugin that support to easily and aesthetically display terraform workspace in zsh prompt, using agnoster theme prompt engine. 

I added a terraform prompt logic, to uniformely support terraform workspace name to be displayed in the agnoster prompt.

I'm currently using this code via /.oh-my-zsh/custom/... structure.

Dependency: 
- [terraform-workspace-prompt](https://github.com/ocontant/terraform-workspace)
  - ohmyzsh PR: Plugins: terraform-workspace-prompt
  
  

If you find this contribution useful, feel free to merge. 

Best Regards,

2023-04-30 17:28 UTC, soheilwikey1 approved these changes
Review

2023-05-01 10:20 UTC, carlosala requested changes

2023-05-01 10:20 UTC, carlosala commented on plugins/terraform-workspace-prompt/README.md
Could we simplify this file to only have `omz` stuff. It should be similar to https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/virtualenv readme file.

2023-05-01 10:20 UTC, carlosala commented on plugins/terraform-workspace-prompt/_terraform
This file should be deleted, it's already present in `terraform` plugin.

2023-05-01 10:20 UTC, carlosala commented on plugins/terraform-workspace-prompt/terraform-workspace.plugin.zsh
> +complete -o nospace -C $(which terraform) terraform
This is not needed, as there's already zsh completion present in `terraform` file.

2024-02-29 21:25 UTC, carlosala commented
Hi! This PR doesn't seem to get a lot of traction, and it seems stale. Closing, thanks for the contribution!

2024-02-29 21:25 UTC, closed without merging