update virtualenvwrapper.plugin.zsh allowing it to run in new panels
ohmyzsh/ohmyzsh pull request #12163
Opened 2024-01-16 01:57 UTC by julioselva

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Add the following hook: `add-zsh-hook precmd workon_cwd` enabling the plugin to run when new windows, panels or tabs are created on the same directory. Otherwise you will need to cd out, then cd in.

## Other comments:

...

2024-01-17 15:44 UTC, carlosala requested changes
What do you think?

2024-01-18 18:25 UTC, julioselva commented on plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh
> +  add-zsh-hook precmd workon_cwd
Much better. In fact, it was a misunderstanding on my part about how hooks work. I will not commit your suggestion just to avoid the comment.

2024-01-18 18:33 UTC, carlosala approved these changes
LGTM!

2024-01-18 18:34 UTC, merged

2024-01-18 18:34 UTC, carlosala commented
Thanks for your contribution!