fix(sublime): allow `sst` to open a new window on wayland
ohmyzsh/ohmyzsh pull request #12194
Opened 2024-02-03 10:55 UTC by Rayzeq

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- Changed the alias `sst` from `sudo subl` to `sudo -EH subl`

## Other comments:

On some (all ?) wayland environnements, like Hyprland,  `sudo subl` is not able to open a new window (although it can open files in an already open window). This fix allow it to work.

2024-02-03 14:54 UTC, carlosala requested changes
I generally like it, I don't think that passing the env would be an issue. I'd say `-H` is not needed, does it work just with `-E`?

2024-02-03 19:34 UTC, Rayzeq commented
The `-H` is necessary. I have no idea why, but sublime doesn't launch without it (maybe because it can't find `~/.config/sublime-text/`, but I'm not sure).

2024-02-04 17:21 UTC, carlosala commented
Let's go for it, shouldn't be an issue!

2024-02-04 17:21 UTC, carlosala approved these changes
LGTM!

2024-02-04 17:21 UTC, merged

2024-02-04 17:21 UTC, carlosala commented
Thanks for your contribution!