feat(jj): completions and prompt utils
ohmyzsh/ohmyzsh pull request #12292
Opened 2024-03-21 02:11 UTC by nasso

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [ ] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

## Changes:

- adds new plugin: `jj`
- adds completions for `jj`
- adds `jj_prompt_template` to easily make prompts

## Other comments:

- we will probably want to add aliases!
- and maybe patch some themes or add new ones? i linked to a patch i made for myself of the `sunaku` theme that can serve as an example

2024-06-20 09:05 UTC, sathishkannan162 commented
Will love to see this feature get merged.

2024-09-19 14:35 UTC, Jarvvski commented
@carlosala could we get this merged?

2025-01-23 19:01 UTC, carlosala requested changes
I like it, and it seems to be getting traction. Let's try to get it merged!
Sorry for the delay!

2025-01-23 19:01 UTC, carlosala commented on plugins/jj/jj.plugin.zsh
> +  fi
Could you refactor this into a `zstyle`-like config? You can find one in `yarn` plugin, for example.

2025-01-24 16:02 UTC, nasso commented
Thank you for the review! I think it things should be better now.

My muscle memory will suffer from the lack of `jst` and `j` but I do agree that they weren't saving enough keystrokes, haha. I don't think I'll even keep them in my own config.

I did add `jla` for `jj log -r 'all()'`, though, as this is a pretty long command that I've had to manually type quite often (sometimes `jj log` doesn't give enough context). I hope this is fine!

Had no idea about `zstyle`, now I realize my environment variable hack was kind of cringe to be honest, haha.

Feel free to mark your comments as resolved if I got them right!

2025-01-25 13:25 UTC, carlosala reviewed
Looks amazing now! What do you think about this small change?

2025-01-25 13:51 UTC, nasso commented on plugins/jj/jj.plugin.zsh
> +alias jsq='jj squash'
That's actually a very good point, i forgot about `jd`! Let's do that

2025-01-26 13:16 UTC, carlosala reviewed
Now it looks amazing! Could you document the aliases in the readme, similar to the `yarn` plugin, for example?
Thanks!

2025-01-26 14:43 UTC, nasso commented
Done! I skipped the `Description` column, I hope that's okay. Most of the aliases are very simple and I feel like it would have been redundant.

2025-03-03 13:18 UTC, ponychicken commented
I tested this locally. Predictions work fine for all commands. In future what would be nice if also branchnames were autocompleted (eg. i type `jj bookmark set m`and hit tab, that it completes to `main` or `michael` or whatever)

2025-03-03 16:13 UTC, carlosala approved these changes
LGTM!

2025-03-03 16:15 UTC, merged

2025-03-03 16:15 UTC, carlosala commented
Thanks for your contribution!

2025-03-03 18:25 UTC, byorgey commented
> In future what would be nice if also branchnames were autocompleted (eg. i type `jj bookmark set m`and hit tab, that it completes to `main` or `michael` or whatever)

Note that `jj` itself now has support for this, with new "dynamic" completions: https://jj-vcs.github.io/jj/latest/install-and-setup/#command-line-completion

2025-03-04 10:06 UTC, nasso commented
> Note that `jj` itself now has support for this, with new "dynamic" completions: https://jj-vcs.github.io/jj/latest/install-and-setup/#command-line-completion

oh that's awesome!! i wish i had known sooner haha
oh well... https://github.com/ohmyzsh/ohmyzsh/pull/13003