feat(macos): `ofd` now opens any directory
ohmyzsh/ohmyzsh pull request #12337
Opened 2024-04-08 15:43 UTC by bartekpacia

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new aliases, I provide a valid use case for all plugin users down below.

I also tested the code locally (see all scenarios above) and it works as expected (`zsh 5.9 (x86_64-apple-darwin23.0)`)

## Changes:

This PR fixes the `ofd` function to not open the `$PWD` in Finder if there are other arguments passed.

I often use `ofd`, but almost equally often I use `ofd <path>`, but in that case, two Finder windows are opened: one with `$PWD`, and the second one with the path I passed. I think this behavior is a small bug, so I changed it.

### Without these changes

- `ofd` opens `$PWD` in Finder
- `ofd .` opens `$PWD` in Finder
- `ofd path1` opens `$PWD` and `path1` in Finder
- `ofd path1 path2` opens `$PWD`, `path1` and `path2` in Finder

### With these changes

- `ofd` opens `$PWD` in Finder
- `ofd .` opens `$PWD` in Finder
- `ofd path1` opens `path1` in Finder
- `ofd path1 path2` opens `path1` and `path2` in Finder

2024-04-08 16:08 UTC, bartekpacia commented
(This is a draft)

2024-04-08 20:15 UTC, carlosala requested changes
Hi! I like the idea! I think it's better just to modify `macos` alias. I'd rather define something like
```zsh
function ofd {
  if (( ! $# )); then
    open_command $PWD
  else
    open_command $@
  fi
}
```
You can modify as well the comment in the code and the README to reflect the new behaviour of the function.

2024-04-08 20:46 UTC, bartekpacia commented
I like it! Thanks!

2024-04-08 20:53 UTC, carlosala reviewed
Could you update the comment on top of the function and the plugin README to match the behaviour of the function as well?
Thanks!

2024-04-08 21:04 UTC, bartekpacia commented
Sure, done!

2024-04-09 10:18 UTC, carlosala approved these changes

2024-04-09 10:19 UTC, merged

2024-04-09 10:19 UTC, carlosala commented
Thanks!