feat(tmux): Name sessions based on the current directory
ohmyzsh/ohmyzsh pull request #12351
Opened 2024-04-13 07:31 UTC by jfpedroza

## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

When `$ZSH_TMUX_AUTONAME_SESSION=true`, name the tmux session after the working directory.

If you are in `~/foo/bar`, the name will be `bar`. If you are in `~/`, the name will be `home`.

2024-04-15 11:11 UTC, carlosala requested changes
I like it! I'm ok with merging it! I'd name `HOME` in caps; it's less common to have a directory called `HOME` than `home`.
The only thing that's missing is a special case for `/`. Maybe `ROOT`?

2024-04-15 20:48 UTC, jfpedroza commented
Never considered opening a session at `/`. I agree with `ROOT`.

2024-04-16 07:51 UTC, carlosala approved these changes

2024-04-16 07:52 UTC, merged

2024-04-16 07:52 UTC, carlosala commented
Thanks for your contribution!