Add aliases for kustomization application
ohmyzsh/ohmyzsh pull request #8738
Opened 2020-03-11 16:01 UTC by mhaligowski

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Adds aliases for applying kustomization directories

2020-06-23 16:55 UTC, mhaligowski commented
Thanks @bartekpacia is there anything I need to do before merging? GH says I need write permission.

2020-06-23 17:01 UTC, bartekpacia commented
Honestly, I'm not sure so I'll ask @larson-carter about this

2020-06-23 18:19 UTC, mcornella commented
Please add the aliases to the plugin README before a merge can happen.

2020-10-23 15:50 UTC, 53jk1 approved these changes

2023-07-10 14:51 UTC, sylwit commented
@mhaligowski I know it's been a while but any chance you fix the README so this PR can be merged. Thank you

2023-07-28 11:03 UTC, carlosala requested changes

2023-07-28 11:03 UTC, carlosala commented on plugins/kubectl/kubectl.plugin.zsh
> +alias kak='kubectl apply -k'
`kak` is the command for [`kakoune` editor](http://kakoune.org/), we'd need another name.

2024-08-01 17:57 UTC, carlosala commented
This PR has been open for a while with important changes requested. Closing for the moment, feel free for anyone to reopen it.
Thanks for your contribution!

2024-08-01 17:57 UTC, closed without merging