adds 1password plugin
ohmyzsh/ohmyzsh pull request #8884
Opened 2020-05-04 16:16 UTC by r-medina

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- adds a [1password](https://1password.com/) plugin

2020-05-04 21:06 UTC, r-medina commented
just realized that `pbcopy` will only work on os x. going to update when i have time later this week

2020-06-29 09:01 UTC, bartekpacia commented
Any update @r-medina?

2020-08-13 21:58 UTC, ianchesal commented on plugins/1password/1password.plugin.zsh
> +function opswd() {
Was about to write this plugin when I saw you had it here already. One change that would be good would be to add completion loading into the plugin. So, at the top of the file:

```
if type op; then
     eval "$(op completion zsh)"; compdef _op op
fi
```

2020-08-13 21:59 UTC, ianchesal commented
I have left a comment for adding in `op` completion into the plugin. Otherwise this looks excellent and would love to see it get merged.

2020-08-14 02:40 UTC, ianchesal commented
Actually, I think all your `if type...` calls need stderr redirect to stdout and stdout dumped to `/dev/null` otherwise you end up with lots messages like:

```
op is /usr/local/bin/op
```

in your terminal with you use this plugin, right?

2020-08-14 02:41 UTC, ianchesal commented on plugins/1password/1password.plugin.zsh
> +    if ! type pbcopy; then
Should be:

```
if ! type pbcopy  >/dev/null 2>&1; then
```

2020-08-14 02:41 UTC, ianchesal commented on plugins/1password/1password.plugin.zsh
> +	if ! type xclip; then
Should be:

```
if ! type xclip  >/dev/null 2>&1; then
```

2020-10-23 15:33 UTC, 53jk1 approved these changes

2021-01-18 10:27 UTC, bartekpacia commented
I'd love to see it merged!

2021-01-18 12:31 UTC, mcornella requested changes
I made code style changes and added a completion function for `opswd`, but there are other possible improvements.

2021-01-18 12:31 UTC, mcornella commented on plugins/1password/1password.plugin.zsh
> +  services=("${(@f)$(op list items --categories Login 2>/dev/null | jq -r '.[].overview.title')}")
The `jq` call could also be removed with
```sh
op list items --categories Login 2>/dev/null | op get item - --fields title 2>/dev/null
```

2022-01-24 14:21 UTC, merged