Added git_files_changed function
ohmyzsh/ohmyzsh pull request #8913
Opened 2020-05-11 16:22 UTC by hemna

This patch adds the git library function for building a
short string that represents the output of git diff --numstat.
This gives theme designers the ability to add the
Number of files changed, number of lines added and number of
lines removed in their prompt for a git repository, while the user's
current working directory is in the git repo.

The new function supports prefix and suffix for each of the
options, files changed, lines added and lines removed.

To colorize the output, you can do something like this in your
theme file

ZSH_THEME_GIT_FILES_CHANGED_PREFIX="%{$fg[yellow]%}"
ZSH_THEME_GIT_FILES_CHANGED_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_LINES_ADDED_PREFIX="%{$fg[green]%}"
ZSH_THEME_GIT_LINES_ADDED_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_LINES_REMOVED_PREFIX="%{$fg[red]%}"
ZSH_THEME_GIT_LINES_REMOVED_SUFFIX="%{$fg[blue]%}"

For example, if there are
3 files changed, 10 lines added and no lines removed you will get
3f:10+

1 files changed, 20 lines added and 6 lines removed:
1f:20+:6-

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:

...

2020-05-20 08:11 UTC, Aloxaf requested changes
Some suggestions.

BTW I am not the maintainer of the project.

2020-05-20 08:11 UTC, Aloxaf commented on lib/git.zsh
> +      output="$ZSH_THEME_GIT_FILES_CHANGED_PREFIX${files}f$ZSH_THEME_GIT_FILES_CHANGED_SUFFIX"
`output` should also be local.

2020-05-27 20:55 UTC, hemna commented on lib/git.zsh
> +    raw=$(command git diff --numstat 2>/dev/null) || return 0
updated thanks!

2020-05-27 20:55 UTC, hemna commented on lib/git.zsh
> +        d=$(echo $line | awk '{ print $2 }')
updated thanks!

2020-05-27 20:55 UTC, hemna commented on lib/git.zsh
> +        (( insertions = $insertions + $i ))
updated thanks!

2020-05-27 20:55 UTC, hemna commented on lib/git.zsh
> +      if [[ $insertions > 0 ]]; then
updated thanks!

2020-05-27 20:55 UTC, hemna commented on lib/git.zsh
> +      if [[ $deletions > 0 ]]; then
updated thanks!

2020-05-27 20:55 UTC, hemna commented on lib/git.zsh
> +      output="$ZSH_THEME_GIT_FILES_CHANGED_PREFIX${files}f$ZSH_THEME_GIT_FILES_CHANGED_SUFFIX"
updated thanks!

2020-06-02 11:00 UTC, mcornella commented
How slow is this on a big change?

2020-10-23 15:25 UTC, 53jk1 approved these changes

2021-01-22 19:58 UTC, hemna commented
Would like to see this merged.

2021-06-01 15:36 UTC, hemna commented
anything holding this up?

2021-06-01 21:25 UTC, TheTechRobo commented
probably mainly the fact that they have a backlog of 532 PRs :sweat_smile:

2021-06-01 21:25 UTC, TheTechRobo commented
also they did ask:

> How slow is this on a big change?

cc @mcornella

2026-09-06 00:32 UTC, robbyrussell commented
Thanks for this, and sorry for the six-year silence... Marc asked you a question in 2020 and you pinged twice without getting a reply, which isn't how this should have gone.

On his question: the function is meaningfully more expensive than what the prompt already does, and the gap grows with the size of the diff, because it walks the full numstat output rather than the summary `git status` gives us. That cost would be paid on every prompt render.

There's also a crash. `git numstat` prints `-` rather than a number for binary files, so in any repo with a binary change the arithmetic fails with `bad math expression: operand expected`.

The third thing is placement. It calls `command git` directly, where the other functions in `lib/git.zsh` go through `__git_prompt_git` so they honor `oh-my-zsh.hide-dirty` and the lock settings.

The binary-file bug and the `__git_prompt_git` call are both easy fixes, but the per-render cost isn't, and in five years no theme in the repo has asked for these numbers. So I'm closing it rather than leave it open for another stretch.

🤖 Co-authored with Claude Code

2026-09-06 00:32 UTC, closed without merging