Streamlined the git pull aliases to 'gu.*' RESOLVES: #8995
ohmyzsh/ohmyzsh pull request #9065
Opened 2020-06-27 04:39 UTC by jose-bonilla

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

This PR Resolves #8995 
- Updated the git pull alias from `gl` to `gu`.
- Updated the git pull upstream master alias from `glum` to `guum`

## Other comments:
N/A

2020-07-01 14:17 UTC, jose-bonilla commented
@bartektartanus I think this is ready to review. 🚀

2020-07-20 16:18 UTC, jpmcb requested changes
+1 to this PR - I find the `gl` aliases confusing and un-intuitive. I would expect it to be `git log`, not `git pull`.

2020-07-20 16:18 UTC, jpmcb commented on plugins/git/git.plugin.zsh
> +alias guum='git pull upstream master'
With the changes ohmyzsh has made with to detecting main / master branch of a repo, I believe this alias will need to also be able to pull from ether. See this https://github.com/ohmyzsh/ohmyzsh/pull/9049

2020-10-23 15:00 UTC, 53jk1 approved these changes

2020-11-17 02:33 UTC, jose-bonilla commented
@jpmcb Fixed that request. 😄

2026-09-08 21:01 UTC, robbyrussell commented
Thanks for this, and sorry for the very long delay in replying.

We ended up going the other direction on this one: #11224 standardized the pull aliases on `gpr*` back in 2022, and `gl` stayed as `git pull`. Renaming `gl` now would break a lot of muscle memory, so I'm closing this rather than merging it. The issue behind it, #8995, is closed too.

Thanks again for taking the time.

2026-09-08 21:01 UTC, closed without merging