Install into ZDOTDIR if set
ohmyzsh/ohmyzsh pull request #9376
Opened 2020-10-23 01:59 UTC by alexpjohnson

## Standards checklist:

- [X] The PR title is descriptive.
- [X] The PR doesn't replicate another PR which is already open.
- [X] I have read the contribution guide and followed all the instructions.
- [X] The code follows the code style guide detailed in the wiki.
- [X] The code is mine or it's from somewhere with an MIT-compatible license.
- [X] The code is efficient, to the best of my ability, and does not waste computer resources.
- [X] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- Makes the install script use the ZDOTDIR as a destination 

## Other comments:

Closes #9001 
...

2020-10-23 14:35 UTC, 53jk1 approved these changes

2020-10-28 04:32 UTC, alexpjohnson commented
@mcornella Would it be possible to get this reviewed?

2021-09-23 15:13 UTC, mcornella commented
If `$ZDOTDIR`, we should also update the references to `~/.zshrc`.

2021-09-23 15:20 UTC, mcornella requested changes
The `setup_zshrc` function should be also updated for `$ZDOTDIR` compatibility.

2021-09-23 15:20 UTC, mcornella commented on tools/install.sh
> +ZSH=${ZSH:-${ZDOTDIR}/.oh-my-zsh}
I'd rather keep this in a single line so we don't define `$ZDOTDIR` and we can later check if it was defined previous to the installer running.

2022-01-25 18:20 UTC, closed without merging