Added example configuration for the AWS plugin
ohmyzsh/ohmyzsh pull request #9422
Opened 2020-11-04 21:21 UTC by robvadai

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] I have read the contribution guide and followed all the instructions.
- [x] The code follows the code style guide detailed in the wiki.
- [x] The code is mine or it's from somewhere with an MIT-compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

Example for AWS profile set up

2020-11-06 13:36 UTC, maksyms requested changes
No comments apart from the below suggestions, tbh. 👍

2020-11-10 21:28 UTC, robvadai commented on plugins/aws/README.md
> +
Added link, please verify it

2020-11-11 14:59 UTC, maksyms approved these changes

2020-11-11 15:00 UTC, maksyms commented
@mcornella This is documentation-only changes, making it clearer how to configure AWS CLI. Good to merge.

2020-11-11 15:14 UTC, merged

2020-11-12 21:00 UTC, robvadai commented
Appreciated guys, thank you