Jira Plugin - Dashboard filter
ohmyzsh/ohmyzsh pull request #9884
Opened 2021-05-03 18:17 UTC by marcelotrevisani

This modification will allow the user to specify a specific dashboard to go to when executed the 'jira dashboard'.

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The PR doesn't replicate another PR which is already open.
- [ ] I have read the contribution guide and followed all the instructions.
- [ ] The code follows the code style guide detailed in the wiki.
- [ ] The code is mine or it's from somewhere with an MIT-compatible license.
- [ ] The code is efficient, to the best of my ability, and does not waste computer resources.
- [ ] The code is stable and I have tested it myself, to the best of my abilities.

## Changes:

- [...]

## Other comments:

...

2023-01-09 19:46 UTC, robbyrussell commented
@marcelotrevisani could you include doc updates for the README to describe how to utilize this proposed feature?

2023-01-09 19:47 UTC, robbyrussell requested changes
Please include README updates for this functionality

2023-01-15 20:12 UTC, marcelotrevisani commented
Hi, I would do it, but I really do not remember anymore about my modifications to be honest. It had passed almost 2 years, 😬 
and I do not use Jira anymore, so, I really do not remember, sorry :/

2023-01-15 21:20 UTC, carlosala commented
Let's close then, thanks for your contribution!

2023-01-15 21:20 UTC, closed without merging